export const LOAN_BROKER_EVENT_BUS = 'LOAN_BROKER_EVENT_BUS';
export const STATE_MACHINE_ARN = 'STATE_MACHINE_ARN';
export const LENDERS_PARAMETER_PATH_PREFIX = 'LENDERS_PARAMETER_PATH_PREFIX';
export const LOAN_BROKER_DATA_BUCKET_NAME = 'LOAN_BROKER_DATA_BUCKET_NAME';
