export const APPLICATION_EVENT_BUS_NAME = 'APPLICATION_EVENT_BUS_NAME';
export const STATE_MACHINE_ARN = 'STATE_MACHINE_ARN';
export const LENDERS_PARAMETER_PATH_PREFIX = 'LENDERS_PARAMETER_PATH_PREFIX';
export const DATA_BUCKET_NAME = 'DATA_BUCKET_NAME';
