export const APPLICATION_EVENT_BUS_NAME = 'APPLICATION_EVENT_BUS_NAME';
export const DATA_BUCKET_NAME = 'DATA_BUCKET_NAME';

export const FIRST_NAME_TEST = '#TEST#';
export const LAST_NAME_LOW_CREDIT_SCORE = '#LOW_CREDIT_SCORE#';
export const LAST_NAME_MEDIUM_CREDIT_SCORE = '#MEDIUM_CREDIT_SCORE#';
export const NI_NUMBER_HAS_BANKRUPTCIES = '#HAS_BANKRUPTCIES#';
export const POSTCODE_NOT_ON_ELECTORAL_ROLL = '#NOT_ON_ELECTORAL_ROLL#';

export const LOW_CREDIT_SCORE = 250;
export const MEDIUM_CREDIT_SCORE = 500;
export const HIGH_CREDIT_SCORE = 750;
