export const LOAN_BROKER_EVENT_BUS = 'LOAN_BROKER_EVENT_BUS';
export const CREDIT_BUREAU_DATA_BUCKET_NAME = 'CREDIT_BUREAU_DATA_BUCKET_NAME';

export const TEST_FIRST_NAME = '#TEST#';
export const TEST_LAST_NAME_FAILED = '#FAILED#';
export const TEST_LAST_NAME_LOW_CREDIT_SCORE = '#LOW_CREDIT_SCORE#';
export const TEST_LAST_NAME_MEDIUM_CREDIT_SCORE = '#MEDIUM_CREDIT_SCORE#';
export const TEST_LAST_NAME_HAS_BANKRUPTCIES = '#HAS_BANKRUPTCIES#';
export const TEST_LAST_NAME_NOT_ON_ELECTORAL_ROLL = '#NOT_ON_ELECTORAL_ROLL#';

export const TEST_LOW_CREDIT_SCORE = 250;
export const TEST_MEDIUM_CREDIT_SCORE = 500;
export const TEST_HIGH_CREDIT_SCORE = 750;
